### ISSUE TITLE
Fitting baseline risk adjusted models?

### ISSUE THREAD

**Issue by timdisher** [gunhanb/nmaINLA#1]
Is it possible to fit baseline risk adjusted models as outlined in Example 6, p.74 of [NICE TSD 3](http://nicedsu.org.uk/wp-content/uploads/2016/03/TSD3-Heterogeneity.final-report.08.05.12.pdf)?

**Comment by gunhanb** [comment]
I tried to fit a baseline risk model before actually, but as far as I know (at least at that time) it is not possible using INLA.
